"""Generate CSS custom properties and Python colour constants from one source.

design/tokens.json is the single source of truth. This writes two outputs from it:

  * the :root {...} block in site/styles.css  (CSS custom properties for the whole site)
  * pipeline/tokens_gen.py                     (Python constants for the OG cards and charts)

Why this exists: og_images.py and two chart generators used to hand-copy the palette out of
styles.css. When the brand blue changed in CSS, the ~5,300 generated OG cards kept the old blue,
because nothing tied the two copies together. Now both are generated from tokens.json, so a colour
can only be changed in one place.

Usage:
    python -m pipeline.build_tokens          # regenerate both outputs
    python -m pipeline.build_tokens --check   # exit 1 if either output is stale (used in CI)

Run `make tokens` after editing tokens.json. `make tokens-check` guards against drift.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS_JSON = ROOT / "design" / "tokens.json"
STYLES_CSS = ROOT / "site" / "styles.css"
TOKENS_PY = ROOT / "pipeline" / "tokens_gen.py"
FIXTURE_CSS = ROOT / "components" / "tokens-final.css"
EMBED_HTML = ROOT / "site" / "embed" / "index.html"
EMBED_START = "/* @tokens:start — generated by `make tokens`. Do not edit by hand. */"
# Only what the widget uses. Keep this list tight: it ships inside other people's pages.
EMBED_TOKENS = (
    "ink",
    "ink-soft",
    "brand",
    "brand-deep",
    "text-on-brand",
    "good",
    "bad",
    "line",
    "bg-alt",
    "surface",
    "r-sm",
    "r-md",
    "r-lg",
    "display",
    "font",
    "mono",
)

START = "  /* @tokens:start"
END = "  /* @tokens:end */"


def _load() -> dict:
    return json.loads(TOKENS_JSON.read_text())


def _py_name(key: str) -> str:
    return key.upper().replace("-", "_")


def render_css_root(tokens: dict) -> str:
    """The exact text of the :root {...} block, markers included."""
    lines = [
        ":root {",
        f"{START} — generated from design/tokens.json by `make tokens`. Do not edit by hand. */",
    ]
    for name, spec in tokens["color"].items():
        lines.append(f"  --{name}: {spec['value']};")
    # Semantic bridge layer: the Stage 3 component variable names, aliased to current values so
    # components render on the live site with no visual change (swapped to the final palette at the
    # Stage 5 cutover). Keys starting with "$" are notes, not tokens.
    for name, value in tokens.get("semantic", {}).items():
        if name.startswith("$"):
            continue
        lines.append(f"  --{name}: {value};")
    for name, value in tokens["scale"].items():
        lines.append(f"  --{name}: {value};")
    # Three font roles, all owned here so no family name is hand-edited in a stylesheet:
    # --display (Source Serif 4) for headings and editorial prose, --font (the platform system
    # stack) for UI, --mono (IBM Plex Mono) for figures and metadata. The faces themselves are
    # self-hosted from site/fonts; see that directory's README.
    lines.append(f"  --display: {tokens['font']['display']};")
    lines.append(f"  --font: {tokens['font']['sans']};")
    lines.append(f"  --mono: {tokens['font']['mono']};")
    lines.append(END)
    lines.append("}")
    return "\n".join(lines)


def render_python(tokens: dict) -> str:
    """The full text of pipeline/tokens_gen.py."""
    colours = tokens["color"]
    shared = {k: v for k, v in colours.items() if v.get("shared")}
    chart = tokens["chart"]

    out = [
        '"""GENERATED by pipeline/build_tokens.py from design/tokens.json. Do not edit by hand.',
        "",
        "Colour constants for the OG cards and charts, kept identical to the CSS custom",
        "properties by generation. Edit design/tokens.json and run `make tokens`.",
        '"""',
        "",
        "# Shared palette (also emitted as CSS custom properties).",
    ]
    for name, spec in shared.items():
        out.append(f'{_py_name(name)} = "{spec["value"]}"')
    out.append("")
    out.append("# Chart-only tints (Python renderers only; not CSS custom properties).")
    for name, spec in chart.items():
        out.append(f'{_py_name(name)} = "{spec["value"]}"')
    out.append("")
    out.append("# Every generated colour, keyed by token name, for lookups and the drift test.")
    out.append("TOKENS = {")
    for name, spec in shared.items():
        out.append(f'    "{name}": "{spec["value"]}",')
    for name, spec in chart.items():
        out.append(f'    "chart.{name}": "{spec["value"]}",')
    out.append("}")
    out.append("")
    return "\n".join(out)


def render_styles(tokens: dict, current: str) -> str:
    """Replace the :root block in styles.css with the generated one, leaving the rest untouched."""
    block = render_css_root(tokens)
    if START in current and END in current:
        pre = current[: current.index(":root {")]
        post = current[current.index(END) + len(END) :]
        # post starts mid-block: drop up to and including the closing brace of :root.
        post = post[post.index("}") + 1 :]
        return pre + block + post
    # First run: no markers yet. Replace the first :root {...} block.
    start = current.index(":root {")
    end = current.index("}", start) + 1
    return current[:start] + block + current[end:]


def render_embed_tokens(tokens: dict, current: str) -> str:
    """Fill the embed widget's :root from the same source, between its @tokens markers.

    The embed is deliberately self-contained: it renders inside someone else's page and cannot
    depend on site/styles.css. That meant a hand-copied palette, which is how it kept the entire
    old blue set through the rebrand while every other surface moved. Generating it removes the
    copy without giving up self-containment.

    Only the tokens the widget actually uses are emitted, not the whole :root: this markup is
    downloaded by third-party pages, so it stays as small as the job allows.
    """
    flat = {name: spec["value"] for name, spec in tokens["color"].items()}
    flat.update({k: v for k, v in tokens.get("semantic", {}).items() if not k.startswith("$")})
    flat.update(tokens["scale"])
    flat["display"] = tokens["font"]["display"]
    flat["font"] = tokens["font"]["sans"]
    flat["mono"] = tokens["font"]["mono"]

    lines = [f"    {EMBED_START}"]
    for name in EMBED_TOKENS:
        if name not in flat:
            raise SystemExit(f"embed wants --{name}, which design/tokens.json does not define")
        lines.append(f"      --{name}: {flat[name]};")
    lines.append(f"    {END.strip()}")
    block = "\n".join(lines)

    pre, rest = current.split(EMBED_START, 1)
    pre = pre[: pre.rindex("\n") + 1]
    post = rest[rest.index(END.strip()) + len(END.strip()) :]
    return pre + block + post


def render_fixture_tokens(tokens: dict) -> str:
    """components/tokens-final.css: the same :root the site serves, for the component fixtures.

    This was hand-maintained, and it drifted badly. Through the forest rebrand it still declared the
    old blue brand, status and surface colours, so the fixtures rendered components in one palette
    while production served another, which defeats the point of having fixtures to review in. The
    old drift test only spot-checked four tokens, so it never noticed. Generating the file from the
    same source as site/styles.css makes the fixtures and the site the same palette by construction.
    """
    return (
        "/* GENERATED by pipeline/build_tokens.py from design/tokens.json. Do not edit by hand.\n"
        " *\n"
        " * Used only by the component fixtures in this folder, which are a development harness and\n"
        " * are not deployed. These are the same custom properties site/styles.css serves, so a\n"
        " * component reviewed in a fixture looks exactly like the same component in production.\n"
        " * Edit design/tokens.json and run `make tokens`.\n"
        " */\n" + render_css_root(tokens) + "\n"
    )


def build(check: bool) -> int:
    tokens = _load()
    want_css = render_styles(tokens, STYLES_CSS.read_text())
    want_py = render_python(tokens)
    want_fixture = render_fixture_tokens(tokens)
    want_embed = render_embed_tokens(tokens, EMBED_HTML.read_text())

    if check:
        stale = []
        if STYLES_CSS.read_text() != want_css:
            stale.append("site/styles.css")
        if not TOKENS_PY.exists() or TOKENS_PY.read_text() != want_py:
            stale.append("pipeline/tokens_gen.py")
        if not FIXTURE_CSS.exists() or FIXTURE_CSS.read_text() != want_fixture:
            stale.append("components/tokens-final.css")
        if EMBED_HTML.read_text() != want_embed:
            stale.append("site/embed/index.html")
        if stale:
            print("STALE (run `make tokens`): " + ", ".join(stale), file=sys.stderr)
            return 1
        print("tokens: generated files are current")
        return 0

    STYLES_CSS.write_text(want_css)
    TOKENS_PY.write_text(want_py)
    FIXTURE_CSS.write_text(want_fixture)
    EMBED_HTML.write_text(want_embed)
    print(
        f"tokens: wrote {STYLES_CSS.relative_to(ROOT)}, {TOKENS_PY.relative_to(ROOT)}, "
        f"{FIXTURE_CSS.relative_to(ROOT)} and {EMBED_HTML.relative_to(ROOT)}"
    )
    return 0


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = ap.parse_args()
    sys.exit(build(args.check))


if __name__ == "__main__":
    main()
