"""GENERATED by pipeline/build_tokens.py from design/tokens.json. Do not edit by hand.

Colour constants for the OG cards and charts, kept identical to the CSS custom
properties by generation. Edit design/tokens.json and run `make tokens`.
"""

# Shared palette (also emitted as CSS custom properties).
INK = "#14203a"
INK_SOFT = "#45526b"
INK_FAINT = "#6b7688"
BG = "#ffffff"
BG_ALT = "#f4f7fb"
BRAND = "#1f6feb"
BRAND_DEEP = "#123a7a"
GOOD = "#0b6b47"
BAD = "#a02012"
BAND_ACCENT = "#ff8c7a"
LINE = "#dde4ee"

# Chart-only tints (Python renderers only; not CSS custom properties).
HOME_BAR = "#8fb2ec"
HOME_TEXT = "#cdd9ee"
HOME_TEXT_DIM = "#93a9cf"
LADDER_BAND = "#dbe7fb"

# Every generated colour, keyed by token name, for lookups and the drift test.
TOKENS = {
    "ink": "#14203a",
    "ink-soft": "#45526b",
    "ink-faint": "#6b7688",
    "bg": "#ffffff",
    "bg-alt": "#f4f7fb",
    "brand": "#1f6feb",
    "brand-deep": "#123a7a",
    "good": "#0b6b47",
    "bad": "#a02012",
    "band-accent": "#ff8c7a",
    "line": "#dde4ee",
    "chart.home-bar": "#8fb2ec",
    "chart.home-text": "#cdd9ee",
    "chart.home-text-dim": "#93a9cf",
    "chart.ladder-band": "#dbe7fb",
}
